# Generated by Django 3.2.16 on 2022-12-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_websitevisitors_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitevisitors',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='websitevisitors',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
