# Generated by Django 3.2.16 on 2022-12-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20221204_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitevisitors',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
