# Generated by Django 3.2.16 on 2022-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_items',
            name='uuid',
            field=models.CharField(default='smcioewmciemnciowemciomewvcew2', max_length=300),
            preserve_default=False,
        ),
    ]
